services:
  backend-api:
    build:
      context: ../..
      dockerfile: participantes/controladores_do_panico_16/Dockerfile
      target: runtime
      args:
        - CGO_ENABLED=0
        - GOOS=linux
        - GOARCH=amd64
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - PORT=8080
    ports:
      - "18020:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "128MB"