version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18020:18020"
    environment:
      PORT: 18020
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    volumes:
      - ../../assets:/app/assets
