version: '3.8'

services:
  api:
    image: your-dockerhub-username/bandidos-do-byte:latest  # Substitua pelo seu repositório Docker
    container_name: bandidos_do_byte_api
    ports:
      - "18020:18020"
    environment:
      - PORT=18020
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    restart: unless-stopped
