version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    container_name: bandidos_do_byte_api
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    restart: unless-stopped
