@baseUrl = http://localhost:18020

### Find a service by intent
POST {{baseUrl}}/api/find-service
Content-Type: application/json

{
  "intent": "quero adquirir um novo cartão de crédito"
}

###

### Health check
GET {{baseUrl}}/api/healthz

###
