version: '3.8'

services:
  galaxia-dos-gophers:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    ports:
      - "18020:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "128MB"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s